### ISSUE TITLE
Question: What's the best way to check if no command was given or if the command given was not a defined command?

### ISSUE THREAD

**Issue by thinsoldier** [thephpleague/climate#100]
At the moment I'm doing:

```
// If no arguments passed, display usage.
if( count($argv) === 1 )
{
	$climate->usage();
	exit;
}
```

Is there any way to get a simple array of whatever was passed as the command if it does not match a defined command?

Also, why is there no full PHPDoc generated documentation?

**Comment by duncan3dc** [comment]
CLImate doesn't have support for "commands" at the moment, only arguments. This is something we'll be looking into soon, but for now the way you're doing it is the only way
