### ISSUE TITLE
CLImates' logo - update needed

### ISSUE THREAD

**Issue by kodejuice** [thephpleague/climate#103]
I think the CLImate logo needs to be updated, it now has over 1 million installs and the logo says "Over 100, 000 Installations".

**Comment by duncan3dc** [comment]
Hi @kodejuice, are you able to provide a new logo image?

**Comment by duncan3dc** [comment]
We've reverted back to the standard logo now with no mention of the number of installs

**Comment by kodejuice** [comment]
Yh, much better ;)
