### ISSUE TITLE
Warning: str_repeat(): Second argument has to be greater than or equal to 0 in... on Windows

### ISSUE THREAD

**Issue by PeeHaa** [thephpleague/climate#106]
I am having the same problem as https://github.com/thephpleague/climate/issues/9#issuecomment-98809057.

Opening a new issue because I think it's a separate problem.

The fix by @sergeizelenyi works for me too.

**Comment by duncan3dc** [comment]
This _should_ be fixed by #64 being merged, can you try out `dev-master` and report back here if it still isn't working, thanks

**Comment by PeeHaa** [comment]
Just tested it on my project with the issue. Working for me 💓
