### ISSUE TITLE
Need to require mbstring extension in composer.json

### ISSUE THREAD

**Issue by garrettw** [thephpleague/climate#109]
As I was just trying to run a library that depends on this one, I discovered that this one was causing a fatal error because it called `mb_strwidth()` in `League\CLImate\TerminalObject\Helper\StringLength::lengthWithoutTags()` – and because I didn't have mbstring installed, the function was not found.

So if someone could add `"ext-mbstring"` to the `require` block in composer.json, that would be lovely. 😄

**Comment by colinodell** [comment]
I've submitted PR #110 with this change.

In the meantime, if you're unable to install `mbstring` you could install the `symfony/polyfill-mbstring` package which provides a userland implementation that only relies on `iconv` (which is usually built into PHP by default).

**Comment by garrettw** [comment]
Thanks! I was able to install it though.
