### ISSUE TITLE
Using both accept and defaultTo blocks user from actually selecting the default value

### ISSUE THREAD

**Issue by Sorcy** [thephpleague/climate#113]
Simple test case:

```
$climate = new League\CLImate\CLImate();

$types = ['s' => 'String', 'b' => 'Bool', 'n' => 'Number', 'h' => 'Host', 'u' => 'URL', 'c' => 'Color', 'e' => 'Enum'];
$input = $climate->input('Please select');
$input->defaultTo('s');
$input->accept(array_keys($types), true);
$type = $input->prompt();
```

This will not allow the user to either select "s" or use just return to select the default value.

The problem seems to be the auto-bolding of the default value, as it is held inside League\CLImate\TerminalObject\Dynamic\Input::$acceptable as "\<bold\>s\</bold\>" instead of just "s"

**Comment by duncan3dc** [comment]
This was fixed by #104
