### ISSUE TITLE
Bug in docs: animation() method

### ISSUE THREAD

**Issue by borgogelli** [thephpleague/climate#114]
`$climate->animation('hello')->enterFrom('right');`
returns
PHP Warning:  file_get_contents(): Filename cannot be empty in /.../vendor/league/climate/src/TerminalObject/Helper/Art.php on line 126

**Comment by duncan3dc** [comment]
The documentation is just using `'hello'` as an example, but we've updated the `animation()` method to handle unknown files now and use the default `404` art (0a7a1259206649441ef733c3461d2843698503ae)
