### ISSUE TITLE
Color support detection is broken on Windows

### ISSUE THREAD

**Issue by kelunik** [thephpleague/climate#119]
https://github.com/thephpleague/climate/blob/4d3ddf97b6db22c76efe2340f603c0d9834ddf72/src/Util/System/Windows.php#L72

^ `getenv()` will never return `true`, this check should probably be `!== false`.

**Comment by duncan3dc** [comment]
Thanks @kelunik, this idea came from Symfony originally so we'll take a look at how they've handled it

**Comment by kelunik** [comment]
I had a look there, it's `!== false` there, but the condition is quite a bit more complex now.

**Comment by joemottershaw** [comment]
Just wondering if there has been any update on this?

**Comment by duncan3dc** [comment]
Not yet, but we'd welcome a pull request with a solution

**Comment by duncan3dc** [comment]
This has been fixed by @azjezz in #128 and will be released in the next version
