### ISSUE TITLE
Proposal: make confirmation dialog more dynamic

### ISSUE THREAD

**Issue by MCStreetguy** [thephpleague/climate#127]
Currently, when the user is prompted for confirmation and types "yes" or "no" as full word, he gets prompted again.
It think it would be more convenient to also accept these as full word and make the comparison case-insensitive.

I already created a pull request to apply the proposed behaviour: #126
I'd really like to hear what you think about that.

Greetings, MCStreetguy

**Comment by duncan3dc** [comment]
Resolved by #126
