### ISSUE TITLE
Wrong regexp in art file search

### ISSUE THREAD

**Issue by comradefuzz** [thephpleague/climate#130]
Case:
* Project called `test` is placed in `/opt/projects/test` directory
* I have two files in `./arts` directory: `logo` and `test`
* When trying to draw `test` art climate prints out `logo` instead

The problem is in [Art helper](https://github.com/thephpleague/climate/blob/master/src/TerminalObject/Helper/Art.php#L111-L139) having wrong regexp:
```
$regex = '~' . preg_quote($art) . $pattern . '~';
``` 
It searches in full path of art file so `/opt/projects/test/arts/logo` is considered acceptable when searching `test` because of project name in its path.
 
File's directory should be removed before applying regexp.

**Comment by duncan3dc** [comment]
This has been fixed in version [3.5.0](https://github.com/thephpleague/climate/releases/tag/3.5.0)
