### ISSUE TITLE
Own exception in arguments parse

### ISSUE THREAD

**Issue by ilyachase** [thephpleague/climate#131]
Hi guys! Great package.
But one thing I'm wondering. Why when we're parsing arguments, we throw basic php's `\Exception` class? I'm talking about that place: `src/Argument/Parser.php:65`. I think it's a good idea to throw some CLImate's own exception in order to developers catch and distinct them from any others.

**Comment by duncan3dc** [comment]
Hi @ilyachase, that's a great idea. I'll do a review, when I get chance, of all the exceptions thrown throughout the library

**Comment by ilyachase** [comment]
@duncan3dc I can help you guys with pull request if you wish.

**Comment by duncan3dc** [comment]
Sure, that would be great!
Just make sure that any new exceptions implement the [interface](https://github.com/thephpleague/climate/blob/f842fa4df89064220063e1e90dc9bcb631aee1cb/src/Exceptions/Exception.php) and extend the previously used exception for backwards compatibility

**Comment by duncan3dc** [comment]
Resolved by #132
