### ISSUE TITLE
confirm default answer

### ISSUE THREAD

**Issue by loranger** [thephpleague/climate#136]
Hello,

I took a look at #13, but it seems my defaultTo call on confirm does not work anymore

```php
$input = $mate->confirm('Do you want to review details?');
$input->defaultTo('y');
var_dump($input->confirmed());
die();
```

returns this

```
Do you want to review details? [y/N]
/Users/loranger/Developer/deploy/src/index.php:78:
bool(false)
```

Did I miss something ?

(I use `"league/climate": "dev-master"` in order to use the spinner)

**Comment by duncan3dc** [comment]
Be careful using `dev-master`, as it hasn't gone through the full regression testing a released version has.
You can always open an issue to ask when a new release will be (to give me a reminder to do one!)
I've identified the cause of this issue and will be releasing a new version shortly
