### ISSUE TITLE
Some hints / examples for multiple menu handling?

### ISSUE THREAD

**Issue by wowcut** [thephpleague/climate#139]
Hi, I really like this little lib because of its minimalism, very quick to get up! Thank you very much! 

However, after adding some functions to a small tool I need to start thinking about how to organize multiple levels of (mostly radiobutton) menus - do you have some hints or examples for how to handle this? Or is there any other library / extension / addon that helps with that? I really would like to make it a little bit more declarative, so menus could be defined with a config file with the option key as function name to execute when selected, but before I get lost I just wanted to ask if I could learn from someone who has solved that already...?

Thanks for your attention!

**Comment by mxdpeep** [comment]
use *nette/neon* to load definitions and populate arrays:

use Nette\Neon\Neon;
$menu = Neon::decode(file_get_contents("menu.neon"));

s pozdravem,

*Filip Oščádal*

**Comment by mxdpeep** [comment]
this is a classic MVC model => stick the Model inside an associative array,
View by CLImate, Controller pretty on your own

play with that and show us the results 💕


s pozdravem,

*Filip Oščádal*

**Comment by wowcut** [comment]
Yes, that might be one way to do it. And that was the reason why I was asking if the author of this library had something on their mind into that direction - it feels like the most important part is missing, and I just want to avoid to do things with a library that was never meant to be [ab-]used in a certain way. Of course "lack of architecture" always means "room for your own ideas" - but at that point it seems wise to ask authors what they have envisioned before hitting walls later on. 

BTW [Laravel Zero](https://github.com/laravel-zero/laravel-zero) is interesting to study - the graphical features are nice to have, but the more important part is the integration into a framework ecosystem - this helps very much in focussing on actual features and not burning to much time with infrastructure code. The Symphony [Console Component](https://symfony.com/doc/current/components/console.html) can be integrated into many things, but the amount of integration work still is quite big. 

Anyway, I wish you nice holidays and all the best for 2019!

**Comment by mxdpeep** [comment]
🎄   ☃  ☃  ☃    🎄


s pozdravem,

*Filip Oščádal*
*https://fredbrooker.gscloud.cz <https://fredbrooker.gscloud.cz>*

**Comment by duncan3dc** [comment]
Hi @wowcut, it sounds like an interesting idea. Perhaps something as simple as attaching a callback to a radio menu item would help? If so I can look into adding that when I get some time

**Comment by duncan3dc** [comment]
Closing due to no response
