### ISSUE TITLE
Single Array Error within $climate->table($X);

### ISSUE THREAD

**Issue by TwinMist** [thephpleague/climate#141]
Hi 
When trying to use $climate->table($X); and the Array of (Associative Arrays) only contains 1 record you get the following error

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to League\CLImate\TerminalObject\Basic\Table::getDefaultColumnWidths() must be of the type array, integer given, called in /scripts/vendor/league/climate/src/TerminalObject/Basic/Table.php on line 206 and defined in /scripts/vendor/league/climate/src/TerminalObject/Basic/Table.php:224
Stack trace:
#0 /scripts/vendor/league/climate/src/TerminalObject/Basic/Table.php(206): League\CLImate\TerminalObject\Basic\Table->getDefaultColumnWidths(6311133)
#1 /scripts/vendor/league/climate/src/TerminalObject/Basic/Table.php(72): League\CLImate\TerminalObject\Basic\Table->getColumnWidths()
#2 /scripts/vendor/league/climate/src/TerminalObject/Router/BasicRouter.php(28): League\CLImate\TerminalObject\Basic\Table->result()
#3 /scripts/vendor/league/climate/src/TerminalObject/Router/Router.php(99): League\CLImate\TerminalObject\Router\BasicRouter->execute(Object(League\CLImate\TerminalObject\Basic\Table))
#4 /scripts/vendor/league/climate/src/CLImate.php(381): League\CLImate\TerminalObjec in /scripts/vendor/league/climate/src/TerminalObject/Basic/Table.php on line 224

**Comment by duncan3dc** [comment]
Hi @TwinMist, thanks for your report, can you provide a short script to reproduce? I've tried the below but it appears to work:
```php
$climate->table([
    [
        "one" => "One",
        "two" => "Two",
        "three" => "Three",
    ],
]);
```

**Comment by TwinMist** [comment]
this array failed
array(4) {
  ["id"]=>
  int(6311133)
  ["sessionid"]=>
  string(32) "d24aab9b31601bba12fa25c2dee5a2bb"
  ["service"]=>
  string(6) "System"
  ["createdDate"]=>
  string(19) "2019-01-06 01:57:05"
}

**Comment by duncan3dc** [comment]
It looks like you must just be passing an associative array (eg the first record), instead of an array containing the first record, for example:
```php
$climate->table([
    "id" => 6311133,
    "sessionid" => "d24aab9b31601bba12fa25c2dee5a2bb",
    "service" =>"System",
    "createdDate" =>"2019-01-06 01:57:05",
]);
```
The above should be done like this instead:
```php

$climate->table([
    [
        "id" => 6311133,
        "sessionid" => "d24aab9b31601bba12fa25c2dee5a2bb",
        "service" =>"System",
        "createdDate" =>"2019-01-06 01:57:05",
    ]
]);
```
I'll see if I can make the error message clearer though :+1:

**Comment by TwinMist** [comment]
so if i have a variable like this 
$data = Array ("self" => $item['self'],
               "id" => $item['id'],
                "type" => $item['type'],
		 "label" => $item['label']			   
		);
$climate->table($data);
how would i get the table to handle it 
Uncaught TypeError: Argument 1 passed to League\CLImate\TerminalObject\Basic\Table::getDefaultColumnWidths() must be of the type array,

thanks thanks

**Comment by duncan3dc** [comment]
In that instance, this should do it:
```php
$climate->table([$data]);
```
