### ISSUE TITLE
CountDown Timer

### ISSUE THREAD

**Issue by TwinMist** [thephpleague/climate#143]
Hi, is it possible you could create a function for a countdown timer?

many thanks

**Comment by duncan3dc** [comment]
Hi @TwinMist, that sounds like a reasonable request, I'll look into it when I get some time

**Comment by TwinMist** [comment]
any update on this?
thanks

**Comment by duncan3dc** [comment]
Hi @TwinMist, can you try out this branch and see what you think:
```sh
composer require league/climate:dev-countdown
```
```php
$climate->countdown("It's happening... ")->from(9)->run();
```

**Comment by TwinMist** [comment]
spot on just what i was after. 
but just one thing,  to have it just counting down with no message you have to do 
$climate->countdown("")->from(9)->run();
if you do
$climate->countdown()->from(9)->run();
you get its starting.....

this correct

Thank you.
