### ISSUE TITLE
Clarify in the docs that $climate->error() does not write to STDERR

### ISSUE THREAD

**Issue by mwgamble** [thephpleague/climate#144]
`$climate->error("error message")` is a "command" that applies a set of pre-defined formatting rules. To actually write to STDERR, one must call `$climate->to("error")->error("error message"). It would be nice if this could be clarified in the documentation. Generally when I work with STDIO wrappers, when there is an "out" method (that writes to STDOUT), there is also an "err" or "error" method alongside it that writes to STDERR, which is why I got confused.

**Comment by duncan3dc** [comment]
Hi @mwgamble, I think it makes sense for `error()` to send to STDERR by default, I'll just have to consider the BC impact. But if not then I'll definitely add some clarification to the docs

**Comment by duncan3dc** [comment]
Unfortunately there isn't a reliable way to do this based on the current API, so I've added a note to the docs: https://climate.thephpleague.com/styling/commands/
