### ISSUE TITLE
[NFR] Clear line

### ISSUE THREAD

**Issue by quasipickle** [thephpleague/climate#145]
It would be helpful to have a `clearLine()` method to empty a line and return the cursor to the beginning of said line.  I know we can call `inline("\r")`, but that just returns the cursor to the beginning and doesn't reset the line.

My use case is I have a script that pulls down a list of messages via the Gmail api.  I'd like to output "Retrieving emails" before I make the api call, then have that line reset to "X emails found" after the retrieval is complete.

Right now my code looks like:
```php
$this->Climate->tab(2)->inline('Retrieving emails');
$Incoming = $this->retrieveEmails();
$this->Climate->inline("\r")->tab(2)->inline("                 ")->inline("\r")->tab(2)->inline(count($Incoming).' emails');
```
and it could look like this:
```php
$this->Climate->tab(2)->inline('Retrieving emails');
$Incoming = $this->retrieveEmails();
$this->Climate->clearLine()->tab(2)->inline(count($Incoming).' emails');
```

**Comment by duncan3dc** [comment]
Hi @quasipickle, I've just added a new feature to support this (and multiple using `clearLine($numberOfLines)`), it will be in the next version released shortly
