### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by TwinMist** [thephpleague/climate#146]
Hi,
is it possible to log all the output from the $climate to a text file?
thanks

**Comment by duncan3dc** [comment]
It sure is, as long as the text file exists you can set it up like so:
```php
$climate = new \League\CLImate\CLImate();

$writer = new \League\CLImate\Util\Writer\File("/tmp/climate.log");
$climate->output->add("log", $writer);
$climate->output->defaultTo("log");
```
Then anything you output will be written to the text file
