### ISSUE TITLE
Spinner not in documentation website

### ISSUE THREAD

**Issue by RyanNerd** [thephpleague/climate#147]
Per issue #70 the Spinner was added in release [3.5.0](https://github.com/thephpleague/climate/releases/tag/3.5.0)

Aside from the above closed issue there isn't any documentation I could find for Spinner.

Thanks for creating and maintaining Climate (what great fun it is to use).

**Comment by everton3x** [comment]
Added documentation for Spinner on PR #207

**Comment by duncan3dc** [comment]
Fixed in 3.10.0 thanks to @everton3x
