### ISSUE TITLE
do not work in windows

### ISSUE THREAD

**Issue by windqyoung** [thephpleague/climate#149]
https://github.com/thephpleague/climate/blob/111b2dee0b743881f93a0858dd0cd9bd69c7933c/src/TerminalObject/Helper/Art.php#L90

change to `preg_quote(\DIRECTORY_SEPARATOR)`

**Comment by duncan3dc** [comment]
This is fixed in [3.5.1](https://github.com/thephpleague/climate/releases/tag/3.5.1) sorry for the delay
