### ISSUE TITLE
Composer satis report an error

### ISSUE THREAD

**Issue by jmt33** [thephpleague/climate#150]
Reading composer.json of league/climate (version-4-wip)                               Skipped branch version-4-wip, "5d91f515d5fc2fec53d26312535fd15539c3da5f:composer.json" does not contain valid JSON
Parse error on line 27:
...am": "^1.4"        "overtrue/phplint":
---------------------^
Expected one of: 'EOF', '}', ':', ',', ']'

**Comment by duncan3dc** [comment]
HI @jmt33, that's not a problem, the branch is a work in progress and is not expected to be fully functioning, or even installable in this case. Satis is just warning you that it couldn't load that branch
