### ISSUE TITLE
Warning: preg_match(): Compilation failed: missing terminating ] for character class at offset

### ISSUE THREAD

**Issue by borgogelli** [thephpleague/climate#153]
Climate version 3.5.0

Error: 
`Warning: preg_match(): Compilation failed: missing terminating ] for character class at offset ...`

The problem is in the [file Art.php at line 119](https://github.com/thephpleague/climate/blob/6ad8e26771305769494697253a1a44f2f2e92bfe/src/TerminalObject/Helper/Art.php#L119)
`$regex = '~' . preg_quote($art) . $pattern . '~';`
doesn't work for me, I should change it in:
$regex = '/' . preg_quote($art) .  '.*/';

**Comment by duncan3dc** [comment]
This is fixed in [3.5.1](https://github.com/thephpleague/climate/releases/tag/3.5.1) sorry for the delay
