### ISSUE TITLE
Draw art filenames

### ISSUE THREAD

**Issue by on2** [thephpleague/climate#155]
I noticed whilst working on pull request #154 that if I use the following code that `the-league-big.txt` is drawn:

```php
$climate = new League\CLImate\CLImate;
$climate->draw('the-league');
```

I would expect `the-league.txt` to be shown. Is this by design or a bug?

**Comment by duncan3dc** [comment]
This is a bug, it's fixed in [3.5.1](https://github.com/thephpleague/climate/releases/tag/3.5.1) now and the filename matching is stricter
