### ISSUE TITLE
When is the next tagged release scheduled?

### ISSUE THREAD

**Issue by RyanNerd** [thephpleague/climate#165]
Either major, minor, or patch?

**Comment by duncan3dc** [comment]
I'll be tagging a minor with PHP 8 support soon

**Comment by duxthefux** [comment]
@duncan3dc any update on that?

**Comment by duncan3dc** [comment]
[3.7.0](https://github.com/thephpleague/climate/releases/tag/3.7.0) tagged and released now :tada:
