### ISSUE TITLE
Allow CLImate to be used in a web context

### ISSUE THREAD

**Issue by airikr-e** [thephpleague/climate#172]
Hi.

I can't get past tis error message. Can't find anything online regarding this for CLImate either. How can I get past this?

Here's what I did: I went to my project's folder and ran `composer require league/climate`. After that, I copied-pasted the code under "Usage" in `README.md` here on GitHub and reloaded the page for my project.

```
require_once 'vendor/autoload.php';
$climate = new \League\CLImate\CLImate;

$climate->red('Whoa now this text is red.');
$climate->blue('Blue? Wow!');
```

```
Warning: Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in /var/www/html/website/vendor/league/climate/src/Util/System/Linux.php on line 90
Fatal error: Uncaught Error: Undefined constant 'STDOUT' in /var/www/html/website/vendor/league/climate/src/Util/Writer/StdOut.php:14 Stack trace: #0 /var/www/html/website/vendor/league/climate/src/Util/Output.php(183): League\CLImate\Util\Writer\StdOut->write() #1 /var/www/html/website/vendor/league/climate/src/TerminalObject/Router/BasicRouter.php(37): League\CLImate\Util\Output->write() #2 /var/www/html/website/vendor/league/climate/src/TerminalObject/Router/Router.php(99): League\CLImate\TerminalObject\Router\BasicRouter->execute() #3 /var/www/html/website/vendor/league/climate/src/CLImate.php(384): League\CLImate\TerminalObject\Router\Router->execute() #4 /var/www/html/website/vendor/league/climate/src/CLImate.php(399): League\CLImate\CLImate->buildTerminalObject() #5 /var/www/html/website/vendor/league/climate/src/CLImate.php(435): League\CLImate\CLImate->routeRemainingMethod() #6 /var/www/html/website/vendor/league/climate/src/CLImate.php(440): League\CLImate\CLImate->__call() #7 /va in /var/www/html/website/vendor/league/climate/src/Util/Writer/StdOut.php on line 14
```

**Comment by RyanNerd** [comment]
I am unable to duplicate this problem. I think from your comment:
>reloaded the page for my project

This indicates to me that you were trying to run the PHP script _as a web app_ and not from the terminal. If you try running this as a web app the constant STDOUT will not exist. [The constant STDOUT only exists if the PHP script is ran as a terminal app](https://stackoverflow.com/a/28898174/4323201). 

Here's what I did:
I'm using Linux Mint 20.1. I opened up a terminal window and performed these commands:

```bash
mkdir testCLImate
cd testClimate
composer require league/climate
```

Opened up my text editor (xed) and created `main.php`:

```php
<?php
require_once 'vendor/autoload.php';
$climate = new \League\CLImate\CLImate;

$climate->red('Whoa now this text is red.');
$climate->blue('Blue? Wow!');
```
Saved `main.php` and in the terminal window executed the script: `php main.php`
output screen shot:

![image](https://user-images.githubusercontent.com/10543911/116765482-95735a00-a9e2-11eb-85ef-4197487ae862.png)


```

**Comment by e-edgren** [comment]
```
<?php

	require_once 'vendor/autoload.php';
	require_once 'site-functions.php';

	$climate = new \League\CLImate\CLImate;
	$climate->json([ 'ip' => getip() ]);

?>
```

`php view-myip.php` do work, but running `curl http://localhost/airikr/view-myip.php` shows the same error as this issue is about. The same applies to when I run it live (`curl https://airikr.me/myip`), but no errors since I have `display_errors Off` for obvious reasons.

**Comment by RyanNerd** [comment]
> ```
> <?php
> 
> 	require_once 'vendor/autoload.php';
> 	require_once 'site-functions.php';
> 
> 	$climate = new \League\CLImate\CLImate;
> 	$climate->json([ 'ip' => getip() ]);
> 
> ?>
> ```
> 
> `php view-myip.php` do work, but running `curl http://localhost/airikr/view-myip.php` shows the same error as this issue is about. The same applies to when I run it live (`curl https://airikr.me/myip`), but no errors since I have `display_errors Off` for obvious reasons.

This appears to be a coding problem outside of CLImate. `The internal code of getip()` sounds like the problem and not CLImate.
What does this code produce?

```php
<?php>
require_once 'vendor/autoload.php';
require_once 'site-functions.php';
$climate = new \League\CLImate\CLImate;
$ipInfo = getip(); // <--- any errors or problems with this line? 
$climate->json(['ip'=>ipInfo]);

**Comment by e-edgren** [comment]
That doesn't matter, unfortunately. I can replace `'ip'=>$ipInfo` with `'ip'=>'test'` and I still get the same error:

```
$ curl http://localhost/airikr/view-myip.php
<br />
<b>Warning</b>:  Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in <b>/var/www/html/airikr/vendor/league/climate/src/Util/System/Linux.php</b> on line <b>90</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Undefined constant 'STDOUT' in /var/www/html/airikr/vendor/league/climate/src/Util/Writer/StdOut.php:14
Stack trace:
#0 /var/www/html/airikr/vendor/league/climate/src/Util/Output.php(183): League\CLImate\Util\Writer\StdOut-&gt;write()
#1 /var/www/html/airikr/vendor/league/climate/src/TerminalObject/Router/BasicRouter.php(37): League\CLImate\Util\Output-&gt;write()
#2 /var/www/html/airikr/vendor/league/climate/src/TerminalObject/Router/Router.php(99): League\CLImate\TerminalObject\Router\BasicRouter-&gt;execute()
#3 /var/www/html/airikr/vendor/league/climate/src/CLImate.php(384): League\CLImate\TerminalObject\Router\Router-&gt;execute()
#4 /var/www/html/airikr/vendor/league/climate/src/CLImate.php(399): League\CLImate\CLImate-&gt;buildTerminalObject()
#5 /var/www/html/airikr/vendor/league/climate/src/CLImate.php(435): League\CLImate\CLImate-&gt;routeRemainingMethod()
#6 /var/www/html/airikr/view-myip.php(8): League\CLImate\CLImate-&gt;_ in <b>/var/www/html/airikr/vendor/league/climate/src/Util/Writer/StdOut.php</b> on line <b>14</b><br />
```

`getip()` is a function that I use to retrieve visitor's IP address. I am using PHP version 7.4.3 on my local web server.

**Comment by duncan3dc** [comment]
@e-edgren What's the purpose of using CLImate there? Wouldn't this be much simpler:
```php
<?php
require_once 'site-functions.php';
$ipInfo = getip();
echo json_encode(['ip' => $ipInfo]);
```

**Comment by e-edgren** [comment]
Sorry for a late response, @duncan3dc. My real use for CLImate is to show information about the weather for my weather service, serenum.org, just like what [wttr.in](https://github.com/chubin/wttr.in) does. To show the IP address is only for a test to see how CLImate works and if I really can use it for this purpose. But as of now, I can't :(

**Comment by duncan3dc** [comment]
Ah I see what you're doing, I'll look into that when I get a moment

**Comment by duncan3dc** [comment]
I've not looked into how this could be properly supported, but I've merged the workaround from @RyanNerd to avoid an exception in one specific part of the code base when expecting to be run in CLI mode. This is available in [3.8.0](https://github.com/thephpleague/climate/releases/tag/3.8.0) now

**Comment by airikr-e** [comment]
The issue persists even today and with version 3.8.x, but with a different error message:

```
Fatal error: Uncaught Error: Undefined constant "STDOUT" in /srv/http/html/website/vendor/league/climate/src/Util/Writer/StdOut.php:14 Stack trace: #0 /srv/http/html/website/vendor/league/climate/src/Util/Output.php(183): League\CLImate\Util\Writer\StdOut->write() #1 /srv/http/html/website/vendor/league/climate/src/TerminalObject/Router/BasicRouter.php(37): League\CLImate\Util\Output->write() #2 /srv/http/html/website/vendor/league/climate/src/TerminalObject/Router/Router.php(99): League\CLImate\TerminalObject\Router\BasicRouter->execute() #3 /srv/http/html/website/vendor/league/climate/src/CLImate.php(385): League\CLImate\TerminalObject\Router\Router->execute() #4 /srv/http/html/website/vendor/league/climate/src/CLImate.php(400): League\CLImate\CLImate->buildTerminalObject() #5 /srv/http/html/website/vendor/league/climate/src/CLImate.php(436): League\CLImate\CLImate->routeRemainingMethod() #6 /srv/http/html/website/test.php(7): League\CLImate\CLImate->__call() #7 {main} thrown in /srv/http/html/website/vendor/league/climate/src/Util/Writer/StdOut.php on line 14
```

**Comment by filerun** [comment]
Old and closed topic, but this might still help somebody.
If you wish to use code written for the command line, from a web context, where the constants like STDOUT are not defined, the following lines before using CLImate will fix this, allowing output to the browser:

```
if(!defined('STDIN'))  define('STDIN',  fopen('php://input',  'rb'));
if(!defined('STDOUT')) define('STDOUT', fopen('php://output', 'wb'));
if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'wb'));
```
