### ISSUE TITLE
Input and confirm has no default values

### ISSUE THREAD

**Issue by gugglegum** [thephpleague/climate#181]
Sometimes it is useful to allow user select default variant just by pressing ENTER. And variants should be printed after question in brackets. For example:
`Are you sure? [y/N] `
Here uppercase `N` means this is default answer.
Or:
`Enter the path of rsa key (/home/user/.ssh/id_rsa): `

**Comment by duncan3dc** [comment]
Have you tried using [defaultTo()](https://climate.thephpleague.com/terminal-objects/input/#default-response) with an input?
```php
$default = '/home/user/.ssh/id_rsa';
$input = $climate->input('Enter the path of rsa key (' . $default . '): ');
$input->defaultTo($default);
$response = $input->prompt();
```
