### ISSUE TITLE
The boldDraw() referenced in the doc, is an unknown method

### ISSUE THREAD

**Issue by borgogelli** [thephpleague/climate#184]
The doc at https://climate.thephpleague.com/terminal-objects/draw/
shows the following example:
`$climate->boldDraw('mug');`
but that method is missing 
Regards

**Comment by mxdpeep** [comment]
$climate->bold()

**Comment by duncan3dc** [comment]
@borgogelli Almost every method is "missing" as they're dynamically called, the main ones are declared in docblocks (using `@method`) but for compound ones (like `boldDraw`) there are far too many possible combinations to define them all.
If you want to use the declared methods then you could do `$climate->bold()->draw('mug')` instead
