### ISSUE TITLE
Fatal error after latest update

### ISSUE THREAD

**Issue by mxdpeep** [thephpleague/climate#185]
PHP Fatal error:  Uncaught TypeError: defined(): Argument #1 ($constant_name) must be of type string, resource given in .../vendor/league/climate/src/Util/System/Linux.php:91

league/climate                    3.8.0

**Comment by duncan3dc** [comment]
Do you have a script to reproduce? And details about the environment that causes this issue?

**Comment by duncan3dc** [comment]
Fixed in [3.8.1](https://github.com/thephpleague/climate/releases/tag/3.8.1) now
