### ISSUE TITLE
Progress: getCurrent() & getTotal()

### ISSUE THREAD

**Issue by quasipickle** [thephpleague/climate#192]
It would be useful to be able to retrieve the current & total values from a progress bar.

My use case is that I define the progress bar in one method in a class, then use it in other methods.  I'd like my label to be updated with the count, ie `(23/1176)` without having to track those numbers separately.

I'm happy to do this & submit a PR, but I wonder if this package is actively maintained?

**Comment by everton3x** [comment]
Added on PR #206 .

**Comment by duncan3dc** [comment]
Fixed in 3.10.0 thanks to @everton3x
