### ISSUE TITLE
Password prompt

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/climate#31]
It would be awesome be have an option for prompting for a password and hiding the characters.

**Comment by davidneimeyer** [comment]
Here's a quick hack:
https://gist.github.com/davidneimeyer/27c984252d2056c3bddc

It's not portable, and _really_ should use (_read: be implemented as part of_) the ```CLImate\Util\System*``` adapters instead of a raw ```exec()```.  Use at your own discretion!

**Comment by rohithmeethal** [comment]
yes we definitely required a password input option, rightn ow I am using text input to get password, which is really bad idea. Please include a linux style password prompt that doesn't show any feed back.
This is really helpful when creating command line installers.

**Comment by joetannenbaum** [comment]
This is now officially tagged in 3.1.0. Unfortunately, still working on a Windows solution....

**Comment by sagikazarmark** [comment]
Symfony console has a solution for that. IIRC @Seldaek created a solution for that.

**Comment by Seldaek** [comment]
Symfony console has a trimmed down version of https://github.com/composer/composer/blob/master/src/Composer/IO/ConsoleIO.php#L255-323 without some of the goodness IMO, so I'd advise you look at that composer link. And yes it requires https://github.com/Seldaek/hidden-input to work reliably on all windows versions. The tricks you might find online are windows XP only, and bash/stty is workable for people that have it installed but that's hardly everyone.

**Comment by Seldaek** [comment]
I am thinking maybe I should extract it in a tiny self-contained version that does just that though, if this shit is gonna get copy pasted everywhere with minor tweaks.. This is dumb.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by Seldaek** [comment]
https://packagist.org/packages/seld/cli-prompt

**Comment by sagikazarmark** [comment]
@Seldaek awesome

**Comment by joetannenbaum** [comment]
Thank you @Seldaek, I'll work on integrating this.

**Comment by joetannenbaum** [comment]
Officially tagged in 3.1.1, thanks again @Seldaek!

**Comment by Seldaek** [comment]
Cool :)
