### ISSUE TITLE
Colors are not appearing in log files in 2.6

### ISSUE THREAD

**Issue by terah** [thephpleague/climate#48]
Hi,

Great library!

Something has changed from 2.5 to 2.6 where colors are no longer being pushed to files.  I have cronjob  which outputs a lot of information to log files with a lot of color so I can easily see problems.  2.6 no longer appears to send the colors to the files when redirecting to a file.

**Comment by joetannenbaum** [comment]
2.6 introduced detection of ansi/non-ansi support, what OS are you running the cronjob on? Support is detected via the `hasAnsiSupport` methods in the following classes:

https://github.com/thephpleague/climate/blob/master/src/Util/System/Linux.php
https://github.com/thephpleague/climate/blob/master/src/Util/System/Windows.php

**Comment by terah** [comment]
Hi Joe,

It's on 64bit Red Hat Enterprise Linux Server release 6.5 (Santiago) and my
Yosemite dev machine.

On 2.5, the output had to be viewed in 'more' or 'tail' for it to read ok.
 'Less' had trouble with it.

In 2.6 it looks fine on stdout but it looks like the color is stripped on
redirection.


Regards,

Terry Cullen
Freelance Senior PHP Programmer/Web Developer
--
Phone 1300-955-838Mobile 04-3836-8032Email terry@terah.com.auWeb
http://www.terah.com.au/Skype terah.com.auG-Talk terry@terah.com.au13
Jarrott St, Chelmer, 4068 QLDTerah Pty Ltd | ACN 135 365 552
<http://www.terah.com.au/>[image: Terah Pty Ltd logo]
<http://www.terah.com.au/>

**Comment by terah** [comment]
These are taken on my Yosemite mac.

With 2.5:
![screenshot 2015-01-13 12 20 48](https://cloud.githubusercontent.com/assets/2120322/5715102/0cc1f12c-9b1f-11e4-8c73-8d7c965d21f9.png)

With 2.6:
![screenshot 2015-01-13 12 22 34](https://cloud.githubusercontent.com/assets/2120322/5715104/145eaeac-9b1f-11e4-8b85-6ec07bfc6556.png)

The terminal is showing as having Ansi support.

**Comment by terah** [comment]
Oh.. It's on php 5.5 too...

**Comment by joetannenbaum** [comment]
Gotcha, thank you for the screenshots, very helpful!

So the culprit is the check for ansi support on Linux (`(function_exists('posix_isatty') && @posix_isatty(STDOUT))`). Since you're piping the output elsewhere, it doesn't detect an interactive terminal and drops the ansi support. Generally, that's a good thing so you don't get a garbled mess, but I can see your use case.

I'll look into layering something in to force ansi support on or off, let me see where it belongs and I'll let you know when it's up.

**Comment by terah** [comment]
Yes... It looks like posix_isatty(STDOUT) is the culprit.  Might need a forceAnsiOutput settings flag?

**Comment by joetannenbaum** [comment]
A `forceAnsiOn` method was just added in 2.6.1, enjoy!

```php
$climate->forceAnsiOn();
```

**Comment by terah** [comment]
Cheers!

**Comment by FoxxMD** [comment]
:+1: Thanks for this.

**Comment by borgogelli** [comment]
Great !
