### ISSUE TITLE
indent tables

### ISSUE THREAD

**Issue by tolry** [thephpleague/climate#51]
It would be great to have the possibilty to indent a table. The tab() method does not work, as it is only inserts a tab, so just the first line (border) would be indented if used like this

``` php
$cli->tab()->table([...])
```

I would be willing to start working on this, if I am not the only one interested in this :smile:

**Comment by duncan3dc** [comment]
Hi @tolry, that does sound interesting and we would welcome a pull request for the feature, as long as it doesn't add too much complexity :+1:

**Comment by tolry** [comment]
@duncan3dc well, that's an old issue, have almost forgotten about it 😃 

If I remember correctly, this would have been quite hard to implement, as `tab()` is completely "stateless" (for the lack of a better word) and having table honour tab() would mean the need to do some kind of untab() afterwards. What I am saying: I do not think that this would fit nicely with the current API as it would be quite some magic behind the scenes. Plus: not enough time to build a prototype for now, sorry. So do not expect a PR from me.

But thank you for the feedback :+1:

**Comment by duncan3dc** [comment]
No problem, I was thinking when we start rendering the table we could pick up the current column position, and then use that column position for each row in the table, but I'm not sure what that would look like code-wise. I'll take a look when I get some time

**Comment by duncan3dc** [comment]
This can be achieved by adding a second "prefix" parameter to the table call:
```php
$climate->table([
    ["A1", "A2", "A3"],
    ["B1", "B2", "B3"],
    ["C1", "C2", "C3"],
], "\t");
```

**Comment by tolry** [comment]
@duncan3dc thanks for adding this (reference if others are interested https://github.com/thephpleague/climate/commit/1a91bfbfa40c9ee5a1a55b06a4a68d223a94b75a)
