### ISSUE TITLE
Enhancing Input

### ISSUE THREAD

**Issue by tolry** [thephpleague/climate#52]
A few improvements I would like to see when using inputs with a list of acceptable responses.
- when `accept()` is used in combination `defaultTo`, highlight the default option (bold, underscore)
- make some kind of quick selection possible, e.g. the first letter of every option (if not yet used) can select this specific entry.

Of course, this additions should be optional (and probably disabled by default to prevent any BC breaks).

Any thoughts on this? I could try and start working on this, if anybody else is interested.

**Comment by joetannenbaum** [comment]
Great idea for bolding the default option, I think I'm going to hold off on the quick select for now, as you can easily just throw the first letter of each option in as acceptable options themselves.

**Comment by tolry** [comment]
Thanks for implementing the bold on defaeultTo.

Short elaboration on the quick select: the idea behind that would be, that Climate also does the normalizing for you.

Example options:

* **p**rocess
* **s**kip
* s**e**lect
* **q**uit

Now the following input should always return "skip"

* skip
* SKIP
* s
* sKip
* ...

**Comment by duncan3dc** [comment]
Hi @tolry, if you'd like to start work on the quick select we'd be interested to see a pull request, but we won't be developing this ourselves at the moment sorry
