### ISSUE TITLE
Get output for later use?

### ISSUE THREAD

**Issue by mattsah** [thephpleague/climate#55]
Is there a way to simply get output and store it in a variable rather than printing direct to screen?  I even tried output buffering, but this didn't seem to grab it.

**Comment by joetannenbaum** [comment]
You could instantiate it with a class that implements `League\CLImate\Util\Writer\WriterInterface` as the `League\CLImate\Util\Writer\StdOut` class does (https://github.com/thephpleague/climate/blob/master/src/Util/Writer/StdOut.php). That way you can catch anything being written and use it however you wish. Does that work for what you need?

**Comment by mattsah** [comment]
@joetannenbaum if I return the output from that method though will it pass back from out?

like if I just return $content; can I then get that from out() or would I have to implement some other method somewhere?  It's not very clear since that one is writing directly to STDOUT.

That said, although I still think the answer would be useful, I gave up for now due to other reasons which I can open issues for, but it didn't seem worth the hassle for what I needed it for straight out of the gate.

**Comment by joetannenbaum** [comment]
This now officially available in the 3.0 release: http://climate.thephpleague.com/output/
