### ISSUE TITLE
Progress bar across methods

### ISSUE THREAD

**Issue by Ortix92** [thephpleague/climate#63]
Is it possible to use the progress bar across methods in a class? As in, from what I understand, I have to use the instance of `progress` and manually add values.

However it seems that I cannot call `$this->climate->progress()->advance(10)` from another method. Which is a bummer :( Or am I missing something here?

**Comment by dshafik** [comment]
@Ortix92 `$this->climate->progress()` returns an instance of `\League\CLImate\TerminalObject\Dynamic\Progress` that represents the progress bar.

You can pass _that_ around and call `->advance()` (or `->current()`) on it from anywhere.

@joetannenbaum FYI, this bug is bogus, and you can close it :)
