### ISSUE TITLE
In usage message, description isn't displayed for positional parameters

### ISSUE THREAD

**Issue by 20after4** [thephpleague/climate#65]
When I specify parameters without a prefix (or longPrefix) the usage message doesn't include them in the verbose help.

It would be very helpful to be able to provide the description of positional parameters, rather than being forced to use a prefix or roll my own help formatting code.

I would provide a pull request but the code is quite difficult to understand and I got lost trying to figure out exactly where to add the functionality.

**Comment by joetannenbaum** [comment]
I'll tag it up in a bit and make it official.
