### ISSUE TITLE
Routing for custom TerminalObjects

### ISSUE THREAD

**Issue by nochso** [thephpleague/climate#66]
Trying to extend CLImate with a custom Table object for example is more difficult than it has to be.

The namespace `League\CLImate\TerminalObject\Router` is relatively confusing.
There's a RouterInterface used by the Basic- and DynamicRouter but those classes are only used by class Router by passing them to the constructor.

Router *requires* exactly these so I can't pass my own:
```php
public function __construct(DynamicRouter $dynamic = null, BasicRouter $basic = null)
```
CLImate then requires that specific router:
```php
public function setRouter(Router $router)
```
Unless I'm missing something, setRouter() is useless as this is all that's allowed, besides passing null:
```php
$cli = new CLImate();
$cli->setRouter(new Router(new DynamicRouter(), new BasicRouter()))
```

So how should I let CLImate know about a custom TerminalObject outside of CLImate?  
What about passing a list of namespaces that are to be tried in order? That way custom classes can be used with a fallback on default CLImate implementations.

Edit: I realize extending any of those classes will work, but it should be easier. Passing an array of RouterInterface implementations to Router and cleaning up a bit should do the trick. I might do this if someone agrees.

**Comment by joetannenbaum** [comment]
I hear you, and I totally agree. Working on a branch (https://github.com/thephpleague/climate/tree/extending) where extending looks something like this:

```php
$climate->extend('Path\To\Your\Custom\Object\SomethingFancy');
```

Then it can be used like anything else:

```php
$climate->somethingFancy('This is something');
```

Only requirement is that the class extends either the Dynamic or Basic interface to ensure that it integrates seamlessly. 

Thoughts? Better?

**Comment by nochso** [comment]
Yes, that would definitely be better.

Personally I don't like passing the FQN as a string because typical IDE functions won't work on those. Maybe pass instantiated objects instead or allow both?

Other than that, all good :+1:

**Comment by joetannenbaum** [comment]
Yeah I toyed with allowing both, probably will still go that direction. Also interesting to allow searching within a namespace as a fallback. I'll let it simmer a little more then finalize and tag it, thanks for the feedback!

**Comment by joetannenbaum** [comment]
Officially tagged in 3.2.0, enjoy! http://climate.thephpleague.com/extending/

**Comment by nochso** [comment]
Thank you :+1:
