### ISSUE TITLE
Is it possible to not clear that last output label on a progress bar?

### ISSUE THREAD

**Issue by JayBizzle** [thephpleague/climate#68]
This line...
https://github.com/thephpleague/climate/blob/master/src/TerminalObject/Dynamic/Progress.php#L169
...prevents the last progress label being displayed, which isn't ideal when you have a label such as

```
========================================================> 100%
(35 of 36) Dumping video__tag_names
```

You never get to see `(36 of 36)`

Is there any way to override this?

**Comment by joetannenbaum** [comment]
That: is a legitimate question. I'm not sure why I ever did that. But I put it back (f8a783cae97fda9030686b0c08df0c3bc2bd41c9), because I definitely see your point.

I'll tag it up soon so it's an official release, thanks for the heads up.
