### ISSUE TITLE
Backspace key doesn't work on inputs after a radio input

### ISSUE THREAD

**Issue by jelofson** [thephpleague/climate#74]
If I use an input of type radio, then later use an input of type input, I can no longer use the backspace key etc. I think this is due to the $this->util->system->exec('stty -icanon');
Perhaps one should call something like $this->util->system->exec('stty sane'); afterwards?
Maybe I am losing it? :)

```
use League\CLImate\CLImate;

$c = new CLImate;
$options = [
		'a',
		'b'
];
$input = $c->radio('What did you have in mind?', $options);

$response = $input->prompt();
exec('stty sane'); // without this, no backspace (^?)
$i = $c->input('hello');
$r = $i->prompt();
// backspace now works
exit;
```

**Comment by joetannenbaum** [comment]
You are not losing it, very much correct. :+1:  Thanks for the catch, I'll throw that in.

**Comment by jelofson** [comment]
Awesome, thanks!

**Comment by mikegioia** [comment]
@jelofson Can you bump the version tag for this? Composer isn't getting the bug fix and I have to direct it to dev-master currently.

**Comment by jelofson** [comment]
@mikegioia It's not my code. I was just the reporter.

**Comment by mikegioia** [comment]
Oh sorry about that. That message was for @joetannenbaum
