### ISSUE TITLE
Apply colors Inputs (CheckBoxes, Radio buttons) ?

### ISSUE THREAD

**Issue by diegoinsalopez** [thephpleague/climate#77]
Hi

I try to set red color to a radio button but the color doesn't apply to the first element in the list, i'm doing something wrong or it's not possible?

Thanks 

![image](https://cloud.githubusercontent.com/assets/487087/11874848/f5ca20e8-a4e1-11e5-9b4d-3d89c5a8ac33.png)

**Comment by joetannenbaum** [comment]
Yup, I was able to replicate this. Looks like you stumbled onto a strange bug, I'll take a look at it!
