### ISSUE TITLE
exec(): Unable to fork [tput cols] in /app/vendor/league/climate/src/Util/System/System.php on line 66

### ISSUE THREAD

**Issue by alexbilbie** [thephpleague/climate#79]
I'm running a small PHP CLI script in a Docker container running on Debian Jessie.

I consistently get the following error every time I run the script and I call `$cli->border();`:

`exec(): Unable to fork [tput cols] in /app/vendor/league/climate/src/Util/System/System.php on line 66`

Any ideas how I can resolve it?

Thanks

**Comment by alexbilbie** [comment]
I should note that calling `tput cols` in the shell prompt outputs a number as expected

**Comment by joetannenbaum** [comment]
Hm, I'm not actually sure. This is the first I've heard of something like this. I'm sure you've seen this, but is this any use to you? http://stackoverflow.com/questions/20648949/php-warning-exec-unable-to-fork

I could wrap the exec call in a try/catch and return a default I suppose. Let me know if the above yields any interesting results.

**Comment by duncan3dc** [comment]
"Unable to fork" normally means the system doesn't have enough available resources to run the program. Presumably the docker container was under-powered
