### ISSUE TITLE
Padding with non latin symbols issue

### ISSUE THREAD

**Issue by mzf** [thephpleague/climate#80]
When i use Russian lang in padding i get different width in lines with same options

![2016-01-13_12-20-35](https://cloud.githubusercontent.com/assets/4039372/12285825/b1d28e06-b9f0-11e5-8cbb-ff84380506b9.png)

**Comment by duncan3dc** [comment]
Hi @mzf, sorry for the delay with your problem, this is fixed by 11beecfee7953fb53629691259117fb070a56cbd
