### ISSUE TITLE
Argument issue when no value is provided

### ISSUE THREAD

**Issue by banago** [thephpleague/climate#84]
@joetannenbaum thanks for this great package. I use CLImate over at [PHPloy](https://github.com/banago/PHPloy). Lately I've run into an issue. I use this argument:

    phploy --sync
    phploy --sync="hash-goes-here"

The second command works fine, the first one causes this notice and fails:

    PHP Notice:  Undefined offset: 1 in phar:///usr/local/bin/deploy/vendor/league/climate/src/Argument/Parser.php on line 195

Here is the implementation of the argument:

    'sync' => [
        'longPrefix' => 'sync',
        'description' => 'Syncs revision to a given version',
        'defaultValue' => 'LAST',
    ]

What seems to be wrong? Is this a bug in the parser?

Thanks a lot,
Baki

**Comment by joetannenbaum** [comment]
Yeah, I see what's going on there. Probably even more of a case to convert this entire argument parsing situation to using `getopt` which would be much clearer/easier/more concise. I'm getting ready for a vacation tomorrow, but I'll see if I can crank it out tonight.

**Comment by banago** [comment]
I really appreciate it, thanks so much.

**Comment by joetannenbaum** [comment]
Hey @banago, I just put a fix into the master branch if you want to check it out. It's a quick fix, not something I'm totally happy with in the long run, but will avoid that error at the very least.

**Comment by banago** [comment]
@joetannenbaum it is fixed. Thank you very much, it means a lot me. :100:

**Comment by banago** [comment]
@joetannenbaum could you tag this fix because I'm asking from 'dev-master' to grab it and it's causing issues with dependencies because of minimum stability. Tag 3.2.1 would be good enough. Thanks.

**Comment by joetannenbaum** [comment]
Tagged. Yeah, I was surprised you went right for the release using dev-master, I was going to tag it after confirmation that it was good, just got caught up in preparing for my trip. 

All set.

**Comment by banago** [comment]
Perfect, thanks very much! :+1:
