### ISSUE TITLE
Building a dynamic extension

### ISSUE THREAD

**Issue by Ooypunk** [thephpleague/climate#95]
Trying to build a dynamic extension, I am testing, and came up with this script:

`
class ConfirmWithDefault extends DynamicTerminalObject {

}

$climate = new CLImate();

$climate->extend('Bus\Tests\ConfirmWithDefault');

$input = $climate->defaultWef('Continue?');

if ($input->confirmed()) {
    $climate->out('confirmed');
} else {
    $climate->out('declined');
}
`

Notice I call "defaultWef" on the CLImate instance; I am reasonably sure this does not exist, yet it does not crash. Instead, I get the following output (whereafter the script stops):
`Continue?

confirmed`

I don't understand, please help.

**Comment by duncan3dc** [comment]
CLImate is built to try and keep going no matter what you throw at it, if it doesn't recognise a method it will assume it's some styling and attempt to apply it, but if that styling doesn't exist then the basic `out()` method is just called with the string passed, so calling `$climate->defaultWef('Continue?')` is the same as calling `$climate->out('Continue?')`
